server:
  port: 8086
spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
    routes:
      - id: vehicles
        uri: lb://vehicle-service
        predicates:
          - Path=/vehicles/**
      - id: quotas
        uri: lb://quota-service
        predicates:
          - Path=/quotas/**
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
